name: aoc-go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install formatter
        run: go install mvdan.cc/gofumpt@latest
      - name: Check format
        run: make -C go format-check
      - name: Install linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Check lint
        run: make -C go lint
      - name: Test all days
        run: make -C go test

